version: "3.9"
services:
  app:
    build: .
    environment:
      - API_KEY=apikey
      - ADDRESSEE=email
    volumes:
      - $HOME/.certs:/the-alpaca-factory/.certs

  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - $HOME/.certs:/the-alpaca-factory/.certs
    depends_on:
      - app